// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpJatsn9esbqsqNtggLyQd1_nclsLRSfA',
    appId: '1:480562449778:android:f5a9aad2e2116ed63d21eb',
    messagingSenderId: '480562449778',
    projectId: 'todo-9ba1b',
    storageBucket: 'todo-9ba1b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGZNtlVp-cWKDqkTNjY14RG_zgb-M_Oss',
    appId: '1:480562449778:ios:98c9759e6fe3b45f3d21eb',
    messagingSenderId: '480562449778',
    projectId: 'todo-9ba1b',
    storageBucket: 'todo-9ba1b.firebasestorage.app',
    iosBundleId: 'com.example.toDoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGZNtlVp-cWKDqkTNjY14RG_zgb-M_Oss',
    appId: '1:480562449778:ios:af6cbaaaddfc20d83d21eb',
    messagingSenderId: '480562449778',
    projectId: 'todo-9ba1b',
    storageBucket: 'todo-9ba1b.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );
}
