
// ===============================
// IMPORTS
// ===============================

// Firebase Authentication package.
// Firebase is a backend service provided by Google.
//
// It handles:
// - User registration
// - User login
// - User logout
// - Password reset
// - User sessions
//
// FirebaseAuth is the class used to interact with authentication.
import 'package:firebase_auth/firebase_auth.dart';

// Needed because we use StreamSubscription later.
import 'dart:async';

// Flutter UI framework.
import 'package:flutter/material.dart';

// Riverpod package.
//
// Riverpod is a state management solution.
//
// Think of Riverpod as a central storage system
// where different parts of the app can share data.
//
// Example:
// Login Screen -----> Riverpod <----- Home Screen
//
// Both screens can access the same data.
import 'package:flutter_riverpod/flutter_riverpod.dart';

// Allows Riverpod code generation using @riverpod.
import 'package:riverpod_annotation/riverpod_annotation.dart';

// GoRouter package.
//
// GoRouter manages navigation between screens.
//
// Example:
//
// SignInScreen
//      ↓
// MainScreen
//
// Instead of manually pushing screens,
// GoRouter manages routes for us.
import 'package:go_router/go_router.dart';

// Import Register screen.
import 'package:to_do_list/features/authenticaiton/presentation/screens/rigester_screen.dart';

// Import Sign In screen.
import 'package:to_do_list/features/authenticaiton/presentation/screens/sign_in_screen.dart';

// Import Main screen.
import 'package:to_do_list/features/task_management/presentation/screens/main.dart';


// ===============================
// GENERATED FILE
// ===============================

// This file is automatically generated by build_runner.
//
// Generated after running:
//
// dart run build_runner build
//
// You DO NOT create this file manually.
//
// Riverpod uses it to generate providers.
part 'router.g.dart';


// ===============================
// GOROUTER REFRESH STREAM
// ===============================

// This class tells GoRouter:
//
// "Hey! Authentication changed.
// Check your routes again."
//
// Example:
//
// User logs in
//      ↓
// Firebase sends event
//      ↓
// GoRouter refreshes
//      ↓
// Redirect user if needed
class GoRouterRefreshStream extends ChangeNotifier {

  // Constructor
  //
  // Receives a Stream.
  //
  // In our case:
  //
  // firebaseAuth.authStateChanges()
  //
  // which fires whenever:
  // - user signs in
  // - user signs out
  GoRouterRefreshStream(Stream<dynamic> stream) {

    // Listen to authentication changes.
    _subscription = stream.listen((_) {

      // Notify GoRouter that something changed.
      notifyListeners();
    });
  }

  // Stores the active stream subscription.
  late final StreamSubscription<dynamic> _subscription;

  @override
  void dispose() {

    // Stop listening when widget is destroyed.
    _subscription.cancel();

    super.dispose();
  }
}


// ===============================
// APP ROUTE NAMES
// ===============================

// Enum = fixed list of values.
//
// Instead of writing:
//
// context.goNamed('main')
//
// we can write:
//
// context.goNamed(AppRoutes.main.name)
//
// Safer because typos are reduced.
enum AppRoutes {
  main,
  signIn,
  register,
}


// ===============================
// FIREBASE AUTH PROVIDER
// ===============================

// Provider = object managed by Riverpod.
//
// This provider gives access to FirebaseAuth.
//
// Anywhere in the app:
//
// ref.watch(firebaseAuthProvider)
//
// returns:
//
// FirebaseAuth.instance
final firebaseAuthProvider = Provider<FirebaseAuth>((ref) {

  // FirebaseAuth.instance is the singleton
  // authentication object for the app.
  return FirebaseAuth.instance;
});


// ===============================
// ROUTER PROVIDER
// ===============================

// @riverpod tells Riverpod:
//
// "Generate a provider for this function."
//
// After generation:
//
// goRouterProvider
//
// becomes available.
@riverpod
GoRouter goRouter(Ref ref) {

  // Get FirebaseAuth from Riverpod.
  final firebaseAuth = ref.watch(firebaseAuthProvider);

  // Return a configured GoRouter.
  return GoRouter(

    // First route the app tries to open.
    //
    // NOTE:
    // redirect() may change this.
    initialLocation: '/main',

    // Prints useful navigation logs.
    debugLogDiagnostics: true,

    // ==========================
    // ROUTE PROTECTION
    // ==========================
    //
    // Runs whenever navigation occurs.
    //
    // Think of it as a security guard.
    redirect: (context, state) {

      // Check if user is logged in.
      //
      // currentUser == null
      // means NOT logged in.
      final isLoggedIn =
          firebaseAuth.currentUser != null;

      // Check if current page is an auth page.
      //
      // /signIn
      // /register
      final isAuthPage =
          state.uri.toString() == '/signIn' ||
          state.uri.toString() == '/register';

      // ------------------------
      // CASE 1
      // ------------------------
      //
      // Logged in user tries to
      // access Sign In or Register.
      //
      // Example:
      //
      // User logged in
      //      ↓
      // /signIn
      //      ↓
      // Redirect to /main
      if (isLoggedIn && isAuthPage) {
        return '/main';
      }

      // ------------------------
      // CASE 2
      // ------------------------
      //
      // User not logged in
      // tries to access MainScreen.
      //
      // Example:
      //
      // User logged out
      //      ↓
      // /main
      //      ↓
      // Redirect to /signIn
      if (!isLoggedIn &&
          state.uri.toString() == '/main') {
        return '/signIn';
      }

      // ------------------------
      // CASE 3
      // ------------------------
      //
      // Everything is allowed.
      return null;
    },

    // ==========================
    // AUTH STATE LISTENER
    // ==========================
    //
    // Listen to Firebase authentication changes.
    //
    // When user logs in or out:
    //
    // authStateChanges()
    //      ↓
    // GoRouterRefreshStream
    //      ↓
    // notifyListeners()
    //      ↓
    // redirect() runs again
    refreshListenable:
        GoRouterRefreshStream(
          firebaseAuth.authStateChanges(),
        ),

    // ==========================
    // APP ROUTES
    // ==========================
    routes: [

      // ------------------------
      // MAIN SCREEN
      // ------------------------
      //
      // URL:
      // /main
      //
      // Screen:
      // MainScreen
      GoRoute(
        path: '/main',

        // Route name.
        name: AppRoutes.main.name,

        // Widget to show.
        builder: (context, state) =>
            const MainScreen(),
      ),

      // ------------------------
      // SIGN IN SCREEN
      // ------------------------
      //
      // URL:
      // /signIn
      //
      // Screen:
      // SignInScreen
      GoRoute(
        path: '/signIn',

        name: AppRoutes.signIn.name,

        builder: (context, state) =>
            const SignInScreen(),
      ),

      // ------------------------
      // REGISTER SCREEN
      // ------------------------
      //
      // URL:
      // /register
      //
      // Screen:
      // RegisterScreen
      GoRoute(
        path: '/register',

        name: AppRoutes.register.name,

        builder: (context, state) =>
            const RegisterScreen(),
      ),
    ],
  );
}


// ====================================================
// BEGINNER FLOW TO FOLLOW IN FUTURE PROJECTS
// ====================================================

/*

STEP 1
----------------------------------
Create your screens.

Example:

SignInScreen
RegisterScreen
MainScreen

Do NOT start with routing.

Create the screens first.



STEP 2
----------------------------------
Set up Firebase Authentication.

Learn:

FirebaseAuth.instance

Important methods:

createUserWithEmailAndPassword()

signInWithEmailAndPassword()

signOut()



STEP 3
----------------------------------
Create Riverpod providers.

Ask:

"What data should be shared?"

Examples:

Authentication
Tasks
User profile

Store those in providers.



STEP 4
----------------------------------
Create routes using GoRouter.

Example:

/signIn
/register
/main

Map each route to a screen.



STEP 5
----------------------------------
Add route protection.

Questions:

Can logged-out users access Main?

NO

Can logged-in users access Sign In?

NO

Add redirect() logic.



STEP 6
----------------------------------
Listen to authentication changes.

Use:

firebaseAuth.authStateChanges()

This tells the app:

User logged in

or

User logged out



STEP 7
----------------------------------
Connect auth changes to GoRouter.

Goal:

When auth changes,
routes automatically update.



STEP 8
----------------------------------
Test all cases.

CASE A

Logged out
    ↓
Open app
    ↓
Should see SignInScreen


CASE B

Logged in
    ↓
Open app
    ↓
Should see MainScreen


CASE C

Logged in
    ↓
Try opening SignInScreen
    ↓
Should redirect to MainScreen


CASE D

Logged out
    ↓
Try opening MainScreen
    ↓
Should redirect to SignInScreen



STEP 9
----------------------------------
Only after all of this works:

Add task management
Add Firestore
Add notifications
Add themes

Authentication and navigation
should be stable first.



MENTAL MODEL
----------------------------------

Firebase
=
Stores user accounts


FirebaseAuth
=
Talks to Firebase authentication


Riverpod
=
Stores and shares app data


Provider
=
A box inside Riverpod


GoRouter
=
Navigation manager


Route
=
A path like /main


Redirect
=
A security guard deciding
whether navigation is allowed


Stream
=
A pipe that continuously sends updates


authStateChanges()
=
A stream that sends updates
when login state changes


GoRouterRefreshStream
=
Bridge between Firebase and GoRouter


Complete flow:

User logs in
      ↓
FirebaseAuth
      ↓
authStateChanges()
      ↓
GoRouterRefreshStream
      ↓
GoRouter refreshes
      ↓
redirect() runs
      ↓
User goes to correct screen

*/
